version: '2.3'
services:
  tensorflowtts:
    build: .
    restart: always
    ports:
      - "47260-47269:47260-47269"
    volumes:
      - .:/workspace
    tty: true
    command: python run_service.py 47260 > run_service.log
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
